FROM {{ namespace }}/{{ image_prefix }}skydive-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block skydive_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

## Agent

{% block skydive_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}
