FROM {{ namespace }}/{{ image_prefix }}skydive-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block skydive_analyzer_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

## analyzer

{% block skydive_analyzer_footer %}{% endblock %}
{% block footer %}{% endblock %}
{{ include_footer }}

USER skydive
