FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% block skydive_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='skydive')}}

RUN curl -o /usr/bin/skydive -L "https://github.com/skydive-project/skydive-binaries/raw/travis-builds/v0.9.0/skydive" \
	&& chmod +x /usr/bin/skydive 


{% block skydive_base_footer %}{% endblock %}

